### ISSUE TITLE
Missing Skeleton Loading Animations for Images

### ISSUE THREAD

**Issue by gautamankoji** [SERVER-X-101/SERVER-X-101#17]
The images on initial load don't look good, so there is a requirement for image skeleton loading:

#### Images loading issue on initial load:

![Screenshot 2024-05-10 222156](https://github.com/SERVER-X-101/SERVER-X-101/assets/120157430/f74cb41c-c9e3-4462-92da-f7a7bec7734f)

![Screenshot 2024-05-10 222209](https://github.com/SERVER-X-101/SERVER-X-101/assets/120157430/9ebf00fa-a8cc-4ff5-885e-d64431e05eeb)

**Comment by aquaticcalf** [comment]
![image](https://github.com/SERVER-X-101/SERVER-X-101/assets/126369826/58bb8bd9-ff18-46ad-89b3-6fd80f7c9563)

**Comment by aquaticcalf** [comment]
two ways to deal with it, not sure which one to choose.
1. make a custom image-skeleton component and wrap all images with that
2. make `img` tag behave that way by adding css and js to handle the animation. 
    - add and remove the `skeleton` class depending on load state of the image.
    - `skeleton` class will have the animation

second way would make things easier, i believe
tried making it the first way till now, had to add the wrapper at many places, it broke stuff sometimes

**Comment by aquaticcalf** [comment]
i am going to proceed with the second method; it is easier to implement and maintain as well. i believe it won't break as often.

**Comment by gautamankoji** [comment]
> i am going to proceed with the second method; it is easier to implement and maintain as well. i believe it won't break as often.



> two ways to deal with it, not sure which one to choose.
> 
> 1. make a custom image-skeleton component and wrap all images with that
> 2. make `img` tag behave that way by adding css and js to handle the animation.
>    
>    * add and remove the `skeleton` class depending on load state of the image.
>    * `skeleton` class will have the animation
> 
> second way would make things easier, i believe tried making it the first way till now, had to add the wrapper at many places, it broke stuff sometimes

Did you make the component in layouts/partials/component_name.html? 
And did you use that component by initializing it using Hugo syntax, i.e., 
`{{ partial "component_name" }}` or `{{ partial "component_name.html" }}`?

**Comment by gautamankoji** [comment]
SERVER-X-101/SERVER-X-101@7ff18e6af39d9dcd5814891aab0e04404cf44087 The issue has been resolved!
